fastlane_version "2.14.2"
default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :test do
    opts = {
        :project => 'test/anim.xcodeproj',
        :scheme => 'animTests',
    }
    scan(opts)
  end

end
